#!/bin/bash

#scan wlan channels
arr=(`sudo  iw dev wlan0 scan | grep freq: | awk '{print $2}' | sort | uniq  `)
echo  ${arr[*]}





#enable monitor mod
sudo iw phy phy1 interface add mon0 type monitor

#set monitor mode up
#echo "Bringing up monitor mode"
sudo ifconfig mon0 up

#echo "setting down wlan1"
sudo ifconfig wlan0 down

#echo "setting down wlan0"
#sudo iw dev wlan0 del


